### ISSUE TITLE
Chest Boat doesn't craft with Quark chests

### ISSUE THREAD

**Issue by cybercatgurrl** [Markus1002/Extra-Boats#2]
Quark changes the "Chest" item to be Oak Chest, Maple Chest, Spruce Chest, etc.. These don't work to craft the Chest Boat. So if Quark is installed you cant craft it. I'm using 1.15.2.

**Comment by Markus1002** [comment]
They do work in the latest version (1.3.2) https://www.curseforge.com/minecraft/mc-mods/extra-boats/files/2924178

**Comment by cybercatgurrl** [comment]
Sorry, I didn’t see that. Cheers.
