### ISSUE TITLE
Chest Boat not accessible

### ISSUE THREAD

**Issue by Burgersim** [Markus1002/Extra-Boats#4]
Hi there, I'm using extraboats-1.3.4-1.15.2 and I noticed that I couldn't open the chest boat (i.e. access the chest in the boat), at least not when using quark as well and using an oak boat and oak chest.

**Comment by Markus1002** [comment]
Try sneaking while you right-click it.

**Comment by Burgersim** [comment]
I did sneak while right clicking. I put down the boat, put the chest inside, then sneaked and right clicked, but it wouldn't open the inventory.

**Comment by Burgersim** [comment]
Btw, is it intentional that crafting a boat with a chest from quark or another supported mod just gives me a boat with a vanilla chest?

I tried crafting a boat with a chest and was able to open that by sneak-right-clicking, so maybe you just can't put a chest in a boat afterwards and use it?

**Comment by Markus1002** [comment]
Yeah its intentional. I don't think it causes any problems.

Quark also adds chest boats that work by putting a chest in it after the boat has been placed down. I'd recommend diabling Quark's chest boats in its config if you have this mod installed.

**Comment by Burgersim** [comment]
Ah ok so then the problem probably actually lies with quark. Thanks for the help ^^

**Comment by Markus1002** [comment]
Np
