### ISSUE TITLE
Blueprint doesn't automatically on curseforge app

### ISSUE THREAD

**Issue by GrandmaPork** [Markus1002/Extra-Boats#50]
When I installed boatload, it crashed my game without telling me why multiple times. I had to go through my entire modlist to figure out the issue

**Comment by Tokrates** [comment]
I think what he/she/it/they/whatever meant to say was, that the dependency for blueprint is missing on curseforge.
Pretty sure there is one explicit line in the log that says:
`[main/ERROR]: Missing mandatory dependencies: structurize, blockui, blueprint`
so it wasn't that hard to find. ;P

**Comment by GrandmaPork** [comment]
I am very new to crash reports and missed it when i looked through it. Also, apparently immersive fx causes issues with any crash report so I gotta remove that and retry
