### ISSUE TITLE
boats cannot be dispensed with dispensers

### ISSUE THREAD

**Issue by thelegitdolt** [Markus1002/Extra-Boats#56]

**Comment by thelegitdolt** [comment]
i lied

**Comment by thelegitdolt** [comment]
(it'd be nice if you could dispense banners onto boats though)

**Comment by thelegitdolt** [comment]
i lied AGAIN. vanilla boats can be dispensed, but the compat ones from the betas can't

**Comment by Markus1002** [comment]
Thank you for this useful information. We will consider implementing the dispensing feature.

**Comment by thelegitdolt** [comment]
i do my best to help the community

**Comment by bageldotjpg** [comment]
Just tested. Vanilla boats can not be dispensed

**Comment by thelegitdolt** [comment]
yes they can

**Comment by thelegitdolt** [comment]
<img width="591" alt="Screen Shot 2023-03-02 at 8 10 21 AM" src="https://user-images.githubusercontent.com/50085439/222485006-69c61522-004b-41b3-8fc4-d54e1d8c598a.png">
