### ISSUE TITLE
Exit code 1 upon startup

### ISSUE THREAD

**Issue by VYL0Z** [Markus1002/Extra-Boats#57]
Hi ! First things first, i hope you're having a great day ! 

So i had interest in this mod when my game closed upon startup with exit code 1 while boatload is installed. The thing is that the game didn't created a crash report so instead, i give you the logs :

-[debug.log](https://github.com/team-abnormals/boatload/files/10371507/debug.log)
-[latest.log](https://github.com/team-abnormals/boatload/files/10371513/latest.log)

Could you highlight me on this ? Cause in my modpack there is around 240 mods so it's probably an incompatiblity issue with another mod. Anyways, tell me if you need any more information(s) about this issue.

Thanks in advance,

VYL0Z.

**Comment by bageldotjpg** [comment]
You need blueprint installed
