### ISSUE TITLE
Feature Suggestion:Adds official compatibility to Quark

### ISSUE THREAD

**Issue by KukaZero** [Markus1002/Extra-Boats#58]
Although it is quite convenient to make a compatibility for the new version of Boatload, we know that Quark will never add other items for the compatibility with other mods. I think that the new development team may bring variables to take over Quark, but I think it is faster and more reasonable to add compatibility by Boatload, just like other mods of Team Abnormal make. Thank you for your continuous efforts,I love your work very much!

**Comment by bageldotjpg** [comment]
Unfortunately, no plans for this at the moment - sorry. We're planning to keep mod support for Boatload outside of Boatload - someone is welcome to make a compatibility add-on or mod though.
