### ISSUE TITLE
[Bug 1.19.2]Hostile Mobs Not Burning in Sunlight

### ISSUE THREAD

**Issue by SaltSouls** [Markus1002/Extra-Boats#64]
## Description
Just as the title says, Boatload seems to be preventing hostile mobs from burning in the sun. I noticed this on my main pack, and just to be sure I tested it with only boatload installed, an it still was occurring. I don't know how this is happening as I would imagine this mod shouldn't get anywhere near touching the code that relates to mobs burning in sunlight.

**EDIT:**
After looking at the changelog for the recent update, I think the issue lies in the recent changes made to the crimson/warped boats. I think when making them not burn, it might be overextending and resulting in more than just those boats not burning.

## Info
**Logs:** [latest](https://gist.github.com/SaltSouls/d287e233b94dd2518f8e2f1f98949ff6) **|** [debug](https://gist.github.com/SaltSouls/7fbedbf4f8663dec1269d797bfab451fl)

**Version:**
Minecraft - 1.19.2
Forge       - 43.2.6
Blueprint  - 6.1.0
Boatload  - 4.2.0

**Comment by wimplaw** [comment]
Just in case I want to add to this bug that i also noticed it effects all players on my server also. You take no damage in lava or any damage from fire.

**Comment by SaltSouls** [comment]
> Just in case I want to add to this bug that i also noticed it effects all players on my server also. You take no damage in lava or any damage from fire.

I think they fixed it, though I wish they would release a hotfix instead of waiting as this is a pretty major game breaking bug. Sure it doesn't cause a crash, but it breaks major game mechanics. I've resulted to disabling the mod in the meantime until it gets fixed.
