### ISSUE TITLE
Can't get horse in large boat

### ISSUE THREAD

**Issue by mightbesusie** [Markus1002/Extra-Boats#67]
im trying everything, i put the boat on land and tried to guide my horse on it, nothing. i put the boat on water and tried to guide my horse on it, nothing. i put the boat on land and rode my horse and put it on the boat, nothing. i did the same thing with water, and still nothing. please help! I'm on 1.16.5 if it helps?

**Comment by sadsawdde21** [comment]
I think it isn't supported for older versions of the mod (1.16.5) and is 1.16+ only, which is honestly a shame that makes this mod a bit useless honestly

**Comment by bageldotjpg** [comment]
This feature was added in a semi-recent 1.19 version, and is not present in 1.16.5. 1.16.5 is also out of support and it has been for a long time, it is too much work to maintain multiple versions while also trying to add new content.

Not sure how it makes the mod useless. There's two other useful boat types and large boats can still hold 4 mobs, just not horses in 1.18 and lower.
